---
title: "DATS6101 Group Project: Predicting Strokes"
author: "Jonathan Giguere, Jesse Borg, Ese Emuraye, Sarah Gates"
date: "December 11th 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(error = FALSE)
```

```{r basicfcn, include=F}
# can add quietly=T option to the require() function
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
```

### Load packages

```{r load-packages, message = FALSE}
loadPkg('ggplot2')
loadPkg('dplyr')
loadPkg('usmap')
```

### Load data

```{r load-data}
load("brfss2013.RData")
```

### Cleaning the data

```{r keeps}
# Choose which variables we want to keep

keeps <- c('X_state', 'imonth', 'genhlth', 'menthlth', 'hlthpln1', 'sleptim1', 'bphigh4', 'bpmeds', 'cholchk', 'cvdinfr4', 'cvdcrhd4', 'cvdstrk3', 'asthma3', 'asthnow', 'addepev2', 'chckidny', 'diabete3', 'veteran3', 'marital', 'educa', 'employ1', 'income2', 'weight2', 'sex', 'pregnant', 'diffwalk', 'smoke100', 'smokday2', 'stopsmk2', 'usenow3', 'alcday5', 'avedrnk2', 'drnk3ge5', 'fruit1', 'fvgreen', 'exerany2', 'prediab1', 'qlmentl2', 'qlstres2', 'drvisits', 'ssbsugar', 'cvdasprn', 'scntwrk1','X_ageg5yr')

brfss_reduced <- brfss2013[keeps]
```

```{r rename}
# Rename the variables to be more descriptive

new_names <- c('state', 'month', 'gen_health', 'mental_health', 'health_coverage', 'sleep_time', 'high_bp', 'bp_meds', 'time_since_cholcheck', 'heart_attack', 'angina', 'stroke', 'asthma', 'has_asthma_now', 'depression', 'kidney_disease', 'diabetes', 'veteran', 'marital_status', 'education_level', 'employment_status', 'income', 'weight', 'sex', 'pregnant', 'difficulty_walk', 'smoke_100', 'freq_smoke', 'stop_smoke_year', 'smokeless_tabac', 'alc_past_30', 'alc_perday_30', 'binge_alc', 'fruit_freq', 'green_veg_freq', 'exercise_30', 'prediabetes', 'depressed_30', 'anxious_30', 'dr_visits_year', 'soda_freq', 'aspirin_daily', 'work_hours_week','age5yr_bucket')

names(brfss_reduced) <- new_names
```

```{r check for NAs}
# Check to see how many missing values for each column

missing_vals <- colSums(is.na(brfss_reduced))
sort(missing_vals)
```

```{r}
# Drop the variables which have too many missing values

brfss_reduced_drops <- subset(brfss_reduced, select = -c(dr_visits_year, prediabetes, binge_alc, alc_perday_30, freq_smoke, bp_meds, aspirin_daily, soda_freq, pregnant, stop_smoke_year, has_asthma_now, work_hours_week, depressed_30, anxious_30))
```

```{r}
# Remove the rows which have na values in any of the remaining variables

brfss_complete <- na.omit(brfss_reduced_drops)
```

```{r}
# Inspect the dataframe

str(brfss_complete)
```

For the factors, we want to change some of the variable factors to be more intuitive/descriptive, start by inspecting the levels for the factors we might want to change.

```{r}
# Check the levels for some varibles

levels(brfss_complete$high_bp)
levels(brfss_complete$employment_status)
levels(brfss_complete$smokeless_tabac)
levels(brfss_complete$diabetes)
```
Change the yes/no factors to 1/0 for model purposes and change other factors in the variables above to make them better grouped.

```{r}
# Change the factor levels for the variables wwe feel would be better off changed

levels(brfss_complete$health_coverage)[levels(brfss_complete$health_coverage) == 'Yes'] <- 1
levels(brfss_complete$health_coverage)[levels(brfss_complete$health_coverage) == 'No'] <- 0

levels(brfss_complete$heart_attack)[levels(brfss_complete$heart_attack) == 'Yes'] <- 1
levels(brfss_complete$heart_attack)[levels(brfss_complete$heart_attack) == 'No'] <- 0

levels(brfss_complete$angina)[levels(brfss_complete$angina) == 'Yes'] <- 1
levels(brfss_complete$angina)[levels(brfss_complete$angina) == 'No'] <- 0

levels(brfss_complete$stroke)[levels(brfss_complete$stroke) == 'Yes'] <- 1
levels(brfss_complete$stroke)[levels(brfss_complete$stroke) == 'No'] <- 0

levels(brfss_complete$asthma)[levels(brfss_complete$asthma) == 'Yes'] <- 1
levels(brfss_complete$asthma)[levels(brfss_complete$asthma) == 'No'] <- 0

levels(brfss_complete$depression)[levels(brfss_complete$depression) == 'Yes'] <- 1
levels(brfss_complete$depression)[levels(brfss_complete$depression) == 'No'] <- 0

levels(brfss_complete$kidney_disease)[levels(brfss_complete$kidney_disease) == 'Yes'] <- 1
levels(brfss_complete$kidney_disease)[levels(brfss_complete$kidney_disease) == 'No'] <- 0

levels(brfss_complete$veteran)[levels(brfss_complete$veteran) == 'Yes'] <- 1
levels(brfss_complete$veteran)[levels(brfss_complete$veteran) == 'No'] <- 0

levels(brfss_complete$difficulty_walk)[levels(brfss_complete$difficulty_walk) == 'Yes'] <- 1
levels(brfss_complete$difficulty_walk)[levels(brfss_complete$difficulty_walk) == 'No'] <- 0

levels(brfss_complete$smoke_100)[levels(brfss_complete$smoke_100) == 'Yes'] <- 1
levels(brfss_complete$smoke_100)[levels(brfss_complete$smoke_100) == 'No'] <- 0

levels(brfss_complete$exercise_30)[levels(brfss_complete$exercise_30) == 'Yes'] <- 1
levels(brfss_complete$exercise_30)[levels(brfss_complete$exercise_30) == 'No'] <- 0

levels(brfss_complete$diabetes)[levels(brfss_complete$diabetes) == "Yes, but female told only during pregnancy"] <- 1
levels(brfss_complete$diabetes)[levels(brfss_complete$diabetes) == "No, pre-diabetes or borderline diabetes"  ] <- 0
levels(brfss_complete$diabetes)[levels(brfss_complete$diabetes) == 'Yes'] <- 1
levels(brfss_complete$diabetes)[levels(brfss_complete$diabetes) == 'No'] <- 0

levels(brfss_complete$high_bp)[levels(brfss_complete$high_bp) == "Yes, but female told only during pregnancy"] <- 1
levels(brfss_complete$high_bp)[levels(brfss_complete$high_bp) == "Told borderline or pre-hypertensive" ] <- 1
levels(brfss_complete$high_bp)[levels(brfss_complete$high_bp) == 'Yes'] <- 1
levels(brfss_complete$high_bp)[levels(brfss_complete$high_bp) == 'No'] <- 0

levels(brfss_complete$employment_status)[levels(brfss_complete$employment_status) == "Employed for wages" ] <- 'Employed'
levels(brfss_complete$employment_status)[levels(brfss_complete$employment_status) == "Out of work for 1 year or more" ] <- 'Unemployed'
levels(brfss_complete$employment_status)[levels(brfss_complete$employment_status) == "Out of work for less than 1 year" ] <- 'Unemployed'

levels(brfss_complete$smokeless_tabac)[levels(brfss_complete$smokeless_tabac) == "Every day" ] <- 1
levels(brfss_complete$smokeless_tabac)[levels(brfss_complete$smokeless_tabac) == "Some days" ] <- 1
levels(brfss_complete$smokeless_tabac)[levels(brfss_complete$smokeless_tabac) == "Not at all" ] <- 0

```

```{r}
# Inspect the structure of the dataframe with changed variables

str(brfss_complete)
```


### Jonathan EDA

```{r states and heart attack data}
#Making dataframe for visualizing heart attacks per state
state_map_df <- brfss_complete %>% select(state, heart_attack) %>% mutate(state = as.character(state)) %>% group_by(state) %>% summarise(sum_ = sum(as.numeric(heart_attack))) %>% filter(state != c('District of Columbia', 'Puerto Rico', 'Guam'))
```

```{r states and heart map}
#Map showing number of heart attacks per
plot_usmap(data = state_map_df, values = "sum_", color = "white") + 
  scale_fill_continuous(name = "Heart Attack Frequency", label = scales::comma) + 
  theme(legend.position = "right")
```

```{r states and participants data}
#Make dataframe showing number of survey particpants by state
participants_map_df <-  brfss_complete %>% group_by(state) %>% summarise(n = n())
```

```{r states and respondents}
#Visualize map of number of participants per state
plot_usmap(data = participants_map_df, values = "n", color = "white") + 
  scale_fill_continuous(name = "Survey Participants by State", label = scales::comma) + 
  theme(legend.position = "right") 
```

```{r heart attacks for different gen_health levels}
#Visualize proportion of respondents with heart attacks by gen_health
ggplot(brfss_complete, aes(x = gen_health, fill = heart_attack)) +
        geom_bar() + 
        ggtitle('Number of participants that have had heart attack among levels of general health') +
        ylab('Total') +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme(axis.text.x = element_text(size = 11, color = 'black')) +
        theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r heart attacks based on health coverage}
#Visualize proportion of respondents with heart attacks by health insurance
ggplot(brfss_complete, aes(x = health_coverage, fill = heart_attack)) +
        geom_bar() + 
        ggtitle('Number of participants that heart attack among people with and without health insurance') +
        ylab('Total') +
        scale_x_discrete(labels= c('Yes', 'No')) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme(axis.text.x = element_text(size = 11, color = 'black')) +
        theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r heart attacks based on health coverage}
#Visualize proportion of respondents with heart attacks by high_bp
ggplot(brfss_complete, aes(x = high_bp, fill = heart_attack)) +
        geom_bar() + 
        ggtitle('Number of participants that heart attack among people with and without high blood pressure') +
        ylab('Total') +
        scale_x_discrete(labels= c('Yes', 'No')) +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme(axis.text.x = element_text(size = 11, color = 'black')) +
        theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```

```{r weight, sleep time, and heart attack}
ggplot(brfss_complete, aes(x=sleep_time, y=as.numeric(weight), color=heart_attack)) +
  geom_point()
```

```{r sleep time and heart attack data}
#Filter out extreme sleep numbers to get ready to visualize
sleep_heartattack_df <- brfss_complete %>% select(sleep_time, heart_attack) %>%
   filter(as.integer(sleep_time)<14) %>%  filter(as.integer(sleep_time)>3) 
```

```{r sleep time and heart attack graph}
#Visualize sleep_time and heart_attack
ggplot(sleep_heartattack_df, aes(x = sleep_time, fill = heart_attack)) +
        geom_bar() + 
        ggtitle('Number of participants that have had heart attack among levels of sleep') +
        ylab('Total') +
        theme_bw() +
        theme(plot.title = element_text(hjust = 0.5)) + 
        theme(axis.text.x = element_text(size = 11, color = 'black')) +
        theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```

```{r}
sleep_heartattack_df
```

```{r}
str(brfss_complete)
min(as.numeric(brfss_complete$weight))
```


