---
title: "DATS6101 Group Project: Predicting Heart Attacks - EDA Code"
author: "Jonathan Giguere, Jesse Borg, Ese Emuraye, Sarah Gates"
date: "December 11th 2019"
output:
  html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(error = FALSE)
```

```{r basicfcn, include=F}
# can add quietly=T option to the require() function
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }
```

Start by loading the packages we know will be needed for the presentation. Then load the brfss 2013 data which is as an RData file as opposed to a csv.

```{r load-packages, message = FALSE}
# Load the packages using the loadPkg function

loadPkg('ggplot2')
loadPkg('dplyr')
loadPkg('usmap')
loadPkg('viridis')
loadPkg('ResourceSelection')
loadPkg('pROC')
loadPkg('pscl')
loadPkg('caret')
loadPkg('car')
```

```{r load-data}
# Load the RData dataset
load("brfss_complete.RData")
```

```{r}
# Show the structure of the cleaned data
str(brfss_complete)
```